apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-conf
data:
  env: |
    MONGO_DSN=mongodb://root:root@mongodb/nest?authSource=admin
    KAFKA_CLIENT_ID=code-delivery
    KAFKA_BROKER=pkc-n00kk.us-east-1.aws.confluent.cloud:9092
    KAFKA_CONSUMER_GROUP_ID=code-delivery
    KAFKA_SASL_USERNAME=D7P7OEEY2TXC6LUZ
    KAFKA_SASL_PASSWORD=7Wrxv4QxPjpTZuguQq/ARXkwhWzC3Vwy7gc9K+Ha1BMS65BsdnXN0Y/K4Hybpb/e
